### PR TITLE
fix: Add retry logic in "_waitForPkamAuthSuccess" to retry when secondary is temporarily not reachable

### LINKED ISSUE #1394: at_activate should retry if atServer isn't reachable
### Describe the bug

Whilst using cloud_init to spin up an AWS instance with NoPorts it failed at the at_activate stage due to the atServer for the device atSign being (temporarily) unreachable:

```log
Checking ... SHOUT|2024-09-26 11:39:09.214993|OnboardingCli|Unexpected exception: Exception: unable to connect to secondary @bareindoornetball on e6697d6a-2567-50a7-9e61-396157b733d8.swarm0001.atsign.zone:15014
[Error] Exception: unable to connect to secondary @bareindoornetball on e6697d6a-2567-50a7-9e61-396157b733d8.swarm0001.atsign.zone:15014
[Error] Enrollment failed.
  Cause: Exception: unable to connect to secondary @bareindoornetball on e6697d6a-2567-50a7-9e61-396157b733d8.swarm0001.atsign.zone:15014
  Please try again or contact support@atsign.com
```

### Steps to reproduce

This will be tricky to reproduce, as the atServer needs to be present for the enrollment, but then not reachable a moment later.

### Expected behavior

`at_activate` retries (at least a few times, possibly with exponential backoff)

### PR DESCRIPTION
**Pull request by sitaram-kalluri**
**- What I did**
- After submitting an enrollment request, retry for couple of times when secondary server is temporarily not reachable.

**- How I did it**
- Introduce a new variable "_maxActivationRetries" which is a final variable which represents the maximum retries
- In "_waitForPkamAuthSuccess" method, catch if an exception is thrown and increment the "retryCounter" until it "maxActivationRetry" is reached. After that re-throw the exception.
- In the `_attemptPkamAuth` method, if enrollment is denied, it returns an `AtEnrollmentException`.  This exception is caught in the catch block of `_waitForPkamAuthSuccess` (which calls `_attemptPkamAuth`),  triggering the retry logic that we want to avoid.  To prevent this, we need to handle `AtEnrollmentException` separately here, which introduces code duplication.
- To handle all the exceptions in one place, moved the existing exception handing logic in _attemptPkamAuth here. With the changes, _attemptPkamAuth do not handle exception. It rethrows and all the exceptions are handled in the _waitForPkamAuthSuccess.

**- How to verify it**
- Tested the changes manually and attaching the test log:

```
/usr/lib/dart/bin/dart --enable-asserts --no-serve-devtools /home/sitaram/IdeaProjects/atsign/core/at_libraries/packages/at_onboarding_cli/bin/activate_cli.dart enroll -s ABC123 -n wavi:rw -p wavi -a @alice🛠 -r vip.ve.atsign.zone -k ~/.atsign/keys/@alice-pkam-local.atKeys -d local-17
Submitting enrollment request
Waiting for approval; will check every 10 seconds
Checking ... Enrollment ID: 0d387d23-e38d-4404-b297-f11adfdd1685
 not approved. Will retry in 10 seconds
Checking ...  not approved. Will retry in 10 seconds
Checking ...  not approved. Will retry in 10 seconds
Checking ... SEVERE|2024-10-07 15:36:23.447566|OnboardingCli|Exception occurred when authenticating the atSign: @alice🛠 caused by HandshakeException: Connection terminated during handshake. Attempting to retry for 1 attempt 
 not approved. Will retry in 10 seconds
Checking ... SEVERE|2024-10-07 15:36:33.462455|OnboardingCli|Exception occurred when authenticating the atSign: @alice🛠 caused by HandshakeException: Connection terminated during handshake. Attempting to retry for 2 attempt 
 not approved. Will retry in 10 seconds
Checking ... SEVERE|2024-10-07 15:46:06.025958|OnboardingCli|Exception occurred when authenticating the atSign: @alice🛠 caused by HandshakeException: Connection terminated during handshake. Attempting to retry for 3 attempt 
 not approved. Will retry in 10 seconds
Checking ... SEVERE|2024-10-07 15:46:16.032858|OnboardingCli|Exception occurred when authenticating the atSign: @alice🛠 caused by HandshakeException: Connection terminated during handshake. Attempting to retry for 4 attempt 
 not approved. Will retry in 10 seconds
Checking ... SEVERE|2024-10-07 15:46:26.040091|OnboardingCli|Exception occurred when authenticating the atSign: @alice🛠 caused by HandshakeException: Connection terminated during handshake. Attempting to retry for 5 attempt 
 not approved. Will retry in 10 seconds
Checking ... SEVERE|2024-10-07 15:46:36.047084|OnboardingCli|Exception occurred when authenticating the atSign: @alice🛠 caused by HandshakeException: Connection terminated during handshake Activation failed after 5 attempts 
[Error] HandshakeException: Connection terminated during handshake
[Error] Enrollment failed.
  Cause: HandshakeException: Connection terminated during handshake
  Please try again or contact support@atsign.com

Process finished with exit code 0

```

**- Description for the changelog**
- fix: Add retry logic in "_waitForPkamAuthSuccess" to retry when secondary is temporarily not reachable

### CODE REVIEW

File: packages/at_onboarding_cli/lib/src/onboard/at_onboarding_service_impl.dart [hunk 1]
```diff
@@ -321,15 +322,28 @@ class AtOnboardingServiceImpl implements AtOnboardingService {
...
       }
-      bool pkamAuthSucceeded = await _attemptPkamAuth(
-        atLookUp,
-        enrollmentIdFromServer,
-      );
+      bool pkamAuthSucceeded = false;
+      try {
+        pkamAuthSucceeded =
+            await _attemptPkamAuth(atLookUp, enrollmentIdFromServer);
+      } catch (e) {
```
Comment (gkc) [inline packages/at_onboarding_cli/lib/src/onboard/at_onboarding_service_impl.dart:351]: Does `_attemptPkamAuth` throw an exception if PKAM auth fails in a "normal" way (i.e. the enrollment has not yet been approved)?

Some code comments explaining what exactly is going on here would be useful

**Review by gkc — CHANGES_REQUESTED** [review]

File: packages/at_onboarding_cli/lib/src/onboard/at_onboarding_service_impl.dart (hunk 1 above)
Comment (sitaram-kalluri) [reply packages/at_onboarding_cli/lib/src/onboard/at_onboarding_service_impl.dart:351]: In the `_attemptPkamAuth` method, if enrollment is denied, it returns an `AtEnrollmentException`.  This exception is caught in the catch block of `_waitForPkamAuthSuccess` (which calls `_attemptPkamAuth`), 
triggering the retry logic that we want to avoid.  To prevent this, we need to handle `AtEnrollmentException` separately here, which introduces code duplication.

To handle all the exceptions in one place, moved the existing exception handing logic in _attemptPkamAuth here. With the changes, _attemptPkamAuth do not handle exception. It rethrows and all the exceptions are handled in the _waitForPkamAuthSuccess.

Comment (gkc) [reply packages/at_onboarding_cli/lib/src/onboard/at_onboarding_service_impl.dart:351]: OK - I'd suggest we now remove _attemptPkamAuth and move its code inline, as _attemptPkamAuth isn't used anywhere else

**Review by gkc — CHANGES_REQUESTED** [review]

File: packages/at_onboarding_cli/lib/src/onboard/at_onboarding_service_impl.dart (hunk 1 above)
Comment (sitaram-kalluri) [reply packages/at_onboarding_cli/lib/src/onboard/at_onboarding_service_impl.dart:351]: Removed the "_attemptPkamAuth" and moved its code inline.

**Review by gkc — APPROVED** [review]
